/**
 * @autogenerated
 */

import FunctionDeclaration from '../nodes/FunctionDeclaration';
import TypeAliasDeclaration from '../nodes/TypeAliasDeclaration';

type Declaration = 
  | FunctionDeclaration
  | TypeAliasDeclaration;

export default Declaration;
