/**
 * @autogenerated
 */

import FunctionDeclaration from '../nodes/FunctionDeclaration';
import ImportStatement from '../nodes/ImportStatement';
import TypeAliasDeclaration from '../nodes/TypeAliasDeclaration';
import VariableDeclaration from '../nodes/VariableDeclaration';

type Declaration = 
  | FunctionDeclaration
  | ImportStatement
  | TypeAliasDeclaration
  | VariableDeclaration;

export default Declaration;
