/**
 * @autogenerated
 */

import ArrayExpression from '../nodes/ArrayExpresison';
import AssignmentExpression from '../nodes/AssignmentExpression';
import Identifier from '../nodes/Identifier';

type Expression = 
  | ArrayExpression
  | AssignmentExpression
  | Identifier;

export default Expression;
