/**
 * @autogenerated
 */

import {CommonJSImportSource} from '../nodes/ImportStatement';
import {EsImportSource} from '../nodes/ImportStatement';
import {NamespaceImportSource} from '../nodes/ImportStatement';

type ImportSource = 
  | CommonJSImportSource
  | EsImportSource
  | NamespaceImportSource;

export default ImportSource;
