/**
 * @autogenerated
 */

import AnyObjectTypeAnnotation from '../nodes/AnyObjectTypeAnnotation';
import AnyTypeAnnotation from '../nodes/AnyTypeAnnotation';
import ArrayExpression from '../nodes/ArrayExpresison';
import ArrayPattern from '../nodes/ArrayPattern';
import ArrayTypeAnnotation from '../nodes/ArrayTypeAnnotation';
import AssignmentExpression from '../nodes/AssignmentExpression';
import AssignmentPattern from '../nodes/AssignmentPattern';
import BinaryExpression from '../nodes/BinaryExpression';
import BooleanTypeAnnotation from '../nodes/BooleanTypeAnnotation';
import CallExpression from '../nodes/CallExpression';
import {CommonJSImportSource} from '../nodes/ImportStatement';
import ConditionalExpression from '../nodes/ConditionalExpression';
import ConditionalType from '../nodes/ConditionalType';
import EmptyTypeAnnotation from '../nodes/EmptyTypeAnnotation';
import {EsImportSource} from '../nodes/ImportStatement';
import ExistsTypeAnnotation from '../nodes/ExistsTypeAnnotation';
import ExportDefault from '../nodes/ExportDefault';
import ExportNamed from '../nodes/ExportNamed';
import ExpressionStatement from '../nodes/ExpressionStatement';
import File from '../nodes/File';
import FunctionDeclaration from '../nodes/FunctionDeclaration';
import FunctionExpression from '../nodes/FunctionExpression';
import FunctionParameter from '../nodes/FunctionParameter';
import FunctionTypeAnnotation from '../nodes/FunctionTypeAnnotation';
import GenericTypeAnnotation from '../nodes/GenericTypeAnnotation';
import Identifier from '../nodes/Identifier';
import IfStatement from '../nodes/IfStatement';
import ImportStatement from '../nodes/ImportStatement';
import ImportTypeAnnotation from '../nodes/ImportTypeAnnotation';
import InferTypeAnnotation from '../nodes/InferTypeAnnotation';
import IntersectionTypeAnnotation from '../nodes/IntersectionTypeAnnotation';
import LiteralTypeAnnotation from '../nodes/LiteralTypeAnnotation';
import LogicalExpression from '../nodes/LogicalExpression';
import MemberExpression from '../nodes/MemberExpression';
import MemberExpressionComputed from '../nodes/MemberExpressionComputed';
import {NamespaceImportSource} from '../nodes/ImportStatement';
import NullLiteral from '../nodes/NullLiteral';
import NumberTypeAnnotation from '../nodes/NumberTypeAnnotation';
import NumericLiteral from '../nodes/NumericLiteral';
import ObjectExpression from '../nodes/ObjectExpression';
import {ObjectExpressionComputedProperty} from '../nodes/ObjectExpression';
import {ObjectExpressionProperty} from '../nodes/ObjectExpression';
import {ObjectExpressionSpreadProperty} from '../nodes/ObjectExpression';
import ObjectPattern from '../nodes/ObjectPattern';
import ObjectTypeAnnotation from '../nodes/ObjectTypeAnnotation';
import {ObjectTypeIndexer} from '../nodes/ObjectTypeAnnotation';
import {ObjectTypeProperty} from '../nodes/ObjectTypeAnnotation';
import {ObjectTypeSpreadProperty} from '../nodes/ObjectTypeAnnotation';
import QualifiedTypeIdentifier from '../nodes/QualifiedTypeIdentifier';
import ReturnStatement from '../nodes/ReturnStatement';
import SpreadElement from '../nodes/SpreadElement';
import StringLiteral from '../nodes/StringLiteral';
import StringTypeAnnotation from '../nodes/StringTypeAnnotation';
import SymbolTypeAnnotation from '../nodes/SymbolTypeAnnotation';
import {TemplateElement} from '../nodes/TemplateLiteral';
import TemplateLiteral from '../nodes/TemplateLiteral';
import ThisExpression from '../nodes/ThisExpression';
import ThisTypeAnnotation from '../nodes/ThisTypeAnnotation';
import TupleTypeAnnotation from '../nodes/TupleTypeAnnotation';
import TypeAliasDeclaration from '../nodes/TypeAliasDeclaration';
import TypeParameter from '../nodes/TypeParameter';
import TypeReferenceAnnotation from '../nodes/TypeReferenceAnnotation';
import TypeofTypeAnnotation from '../nodes/TypeofTypeAnnotation';
import UnaryExpression from '../nodes/UnaryExpression';
import UnionTypeAnnotation from '../nodes/UnionTypeAnnotation';
import UnknownTypeAnnotation from '../nodes/UnknownTypeAnnotation';
import VariableDeclaration from '../nodes/VariableDeclaration';
import VoidTypeAnnotation from '../nodes/VoidTypeAnnotation';

type Node = 
  | AnyObjectTypeAnnotation
  | AnyTypeAnnotation
  | ArrayExpression
  | ArrayPattern
  | ArrayTypeAnnotation
  | AssignmentExpression
  | AssignmentPattern
  | BinaryExpression
  | BooleanTypeAnnotation
  | CallExpression
  | CommonJSImportSource
  | ConditionalExpression
  | ConditionalType
  | EmptyTypeAnnotation
  | EsImportSource
  | ExistsTypeAnnotation
  | ExportDefault
  | ExportNamed
  | ExpressionStatement
  | File
  | FunctionDeclaration
  | FunctionExpression
  | FunctionParameter
  | FunctionTypeAnnotation
  | GenericTypeAnnotation
  | Identifier
  | IfStatement
  | ImportStatement
  | ImportTypeAnnotation
  | InferTypeAnnotation
  | IntersectionTypeAnnotation
  | LiteralTypeAnnotation
  | LogicalExpression
  | MemberExpression
  | MemberExpressionComputed
  | NamespaceImportSource
  | NullLiteral
  | NumberTypeAnnotation
  | NumericLiteral
  | ObjectExpression
  | ObjectExpressionComputedProperty
  | ObjectExpressionProperty
  | ObjectExpressionSpreadProperty
  | ObjectPattern
  | ObjectTypeAnnotation
  | ObjectTypeIndexer
  | ObjectTypeProperty
  | ObjectTypeSpreadProperty
  | QualifiedTypeIdentifier
  | ReturnStatement
  | SpreadElement
  | StringLiteral
  | StringTypeAnnotation
  | SymbolTypeAnnotation
  | TemplateElement
  | TemplateLiteral
  | ThisExpression
  | ThisTypeAnnotation
  | TupleTypeAnnotation
  | TypeAliasDeclaration
  | TypeParameter
  | TypeReferenceAnnotation
  | TypeofTypeAnnotation
  | UnaryExpression
  | UnionTypeAnnotation
  | UnknownTypeAnnotation
  | VariableDeclaration
  | VoidTypeAnnotation;

export default Node;
