/**
 * @autogenerated
 */

import AnyTypeAnnotation from '../nodes/AnyTypeAnnotation';
import ArrayExpression from '../nodes/ArrayExpresison';
import ArrayTypeAnnotation from '../nodes/ArrayTypeAnnotation';
import AssignmentExpression from '../nodes/AssignmentExpression';
import BooleanTypeAnnotation from '../nodes/BooleanTypeAnnotation';
import EmptyTypeAnnotation from '../nodes/EmptyTypeAnnotation';
import ExistsTypeAnnotation from '../nodes/ExistsTypeAnnotation';
import FunctionTypeAnnotation from '../nodes/FunctionTypeAnnotation';
import Identifier from '../nodes/Identifier';
import ImportTypeAnnotation from '../nodes/ImportTypeAnnotation';
import InferTypeAnnotation from '../nodes/InferTypeAnnotation';
import IntersectionTypeAnnotation from '../nodes/IntersectionTypeAnnotation';
import LiteralTypeAnnotation from '../nodes/LiteralTypeAnnotation';
import NumberTypeAnnotation from '../nodes/NumberTypeAnnotation';
import ObjectTypeAnnotation from '../nodes/ObjectTypeAnnotation';
import {ObjectTypeIndexer} from '../nodes/ObjectTypeAnnotation';
import {ObjectTypeProperty} from '../nodes/ObjectTypeAnnotation';
import {ObjectTypeSpreadProperty} from '../nodes/ObjectTypeAnnotation';
import QualifiedTypeIdentifier from '../nodes/QualifiedTypeIdentifier';
import SpreadElement from '../nodes/SpreadElement';
import StringTypeAnnotation from '../nodes/StringTypeAnnotation';
import SymbolTypeAnnotation from '../nodes/SymbolTypeAnnotation';
import ThisTypeAnnotation from '../nodes/ThisTypeAnnotation';
import TupleTypeAnnotation from '../nodes/TupleTypeAnnotation';
import TypeReferenceAnnotation from '../nodes/TypeReferenceAnnotation';
import TypeofTypeAnnotation from '../nodes/TypeofTypeAnnotation';
import UnionTypeAnnotation from '../nodes/UnionTypeAnnotation';
import UnknownTypeAnnotation from '../nodes/UnknownTypeAnnotation';

type Node = 
  | AnyTypeAnnotation
  | ArrayExpression
  | ArrayTypeAnnotation
  | AssignmentExpression
  | BooleanTypeAnnotation
  | EmptyTypeAnnotation
  | ExistsTypeAnnotation
  | FunctionTypeAnnotation
  | Identifier
  | ImportTypeAnnotation
  | InferTypeAnnotation
  | IntersectionTypeAnnotation
  | LiteralTypeAnnotation
  | NumberTypeAnnotation
  | ObjectTypeAnnotation
  | ObjectTypeIndexer
  | ObjectTypeProperty
  | ObjectTypeSpreadProperty
  | QualifiedTypeIdentifier
  | SpreadElement
  | StringTypeAnnotation
  | SymbolTypeAnnotation
  | ThisTypeAnnotation
  | TupleTypeAnnotation
  | TypeReferenceAnnotation
  | TypeofTypeAnnotation
  | UnionTypeAnnotation
  | UnknownTypeAnnotation;

export default Node;
