/**
 * @autogenerated
 */

import {ObjectTypeIndexer} from '../nodes/ObjectTypeAnnotation';
import {ObjectTypeProperty} from '../nodes/ObjectTypeAnnotation';
import {ObjectTypeSpreadProperty} from '../nodes/ObjectTypeAnnotation';

type ObjectTypeElement = 
  | ObjectTypeIndexer
  | ObjectTypeProperty
  | ObjectTypeSpreadProperty;

export default ObjectTypeElement;
