/**
 * @autogenerated
 */

import {ObjectExpressionComputedProperty} from '../nodes/ObjectExpression';
import {ObjectExpressionProperty} from '../nodes/ObjectExpression';
import {ObjectExpressionSpreadProperty} from '../nodes/ObjectExpression';

type ObjectExpressionElement = 
  | ObjectExpressionComputedProperty
  | ObjectExpressionProperty
  | ObjectExpressionSpreadProperty;

export default ObjectExpressionElement;
