/**
 * @autogenerated
 */

import ArrayPattern from '../nodes/ArrayPattern';
import AssignmentPattern from '../nodes/AssignmentPattern';
import Identifier from '../nodes/Identifier';
import ObjectPattern from '../nodes/ObjectPattern';

type Pattern = 
  | ArrayPattern
  | AssignmentPattern
  | Identifier
  | ObjectPattern;

export default Pattern;
