/**
 * @autogenerated
 */

import ExpressionStatement from '../nodes/ExpressionStatement';
import TypeAliasDeclaration from '../nodes/TypeAliasDeclaration';

type Statement = 
  | ExpressionStatement
  | TypeAliasDeclaration;

export default Statement;
