/**
 * @autogenerated
 */

import ExportDefault from '../nodes/ExportDefault';
import ExportNamed from '../nodes/ExportNamed';
import ExpressionStatement from '../nodes/ExpressionStatement';
import TypeAliasDeclaration from '../nodes/TypeAliasDeclaration';

type Statement = 
  | ExportDefault
  | ExportNamed
  | ExpressionStatement
  | TypeAliasDeclaration;

export default Statement;
