/**
 * @autogenerated
 */

import AnyObjectTypeAnnotation from '../nodes/AnyObjectTypeAnnotation';
import AnyTypeAnnotation from '../nodes/AnyTypeAnnotation';
import ArrayTypeAnnotation from '../nodes/ArrayTypeAnnotation';
import BooleanTypeAnnotation from '../nodes/BooleanTypeAnnotation';
import ConditionalType from '../nodes/ConditionalType';
import EmptyTypeAnnotation from '../nodes/EmptyTypeAnnotation';
import ExistsTypeAnnotation from '../nodes/ExistsTypeAnnotation';
import FunctionTypeAnnotation from '../nodes/FunctionTypeAnnotation';
import GenericTypeAnnotation from '../nodes/GenericTypeAnnotation';
import Identifier from '../nodes/Identifier';
import ImportTypeAnnotation from '../nodes/ImportTypeAnnotation';
import InferTypeAnnotation from '../nodes/InferTypeAnnotation';
import IntersectionTypeAnnotation from '../nodes/IntersectionTypeAnnotation';
import LiteralTypeAnnotation from '../nodes/LiteralTypeAnnotation';
import NumberTypeAnnotation from '../nodes/NumberTypeAnnotation';
import ObjectTypeAnnotation from '../nodes/ObjectTypeAnnotation';
import QualifiedTypeIdentifier from '../nodes/QualifiedTypeIdentifier';
import StringTypeAnnotation from '../nodes/StringTypeAnnotation';
import SymbolTypeAnnotation from '../nodes/SymbolTypeAnnotation';
import ThisTypeAnnotation from '../nodes/ThisTypeAnnotation';
import TupleTypeAnnotation from '../nodes/TupleTypeAnnotation';
import TypeReferenceAnnotation from '../nodes/TypeReferenceAnnotation';
import TypeofTypeAnnotation from '../nodes/TypeofTypeAnnotation';
import UnionTypeAnnotation from '../nodes/UnionTypeAnnotation';
import UnknownTypeAnnotation from '../nodes/UnknownTypeAnnotation';
import VoidTypeAnnotation from '../nodes/VoidTypeAnnotation';

type TypeAnnotation = 
  | AnyObjectTypeAnnotation
  | AnyTypeAnnotation
  | ArrayTypeAnnotation
  | BooleanTypeAnnotation
  | ConditionalType
  | EmptyTypeAnnotation
  | ExistsTypeAnnotation
  | FunctionTypeAnnotation
  | GenericTypeAnnotation
  | Identifier
  | ImportTypeAnnotation
  | InferTypeAnnotation
  | IntersectionTypeAnnotation
  | LiteralTypeAnnotation
  | NumberTypeAnnotation
  | ObjectTypeAnnotation
  | QualifiedTypeIdentifier
  | StringTypeAnnotation
  | SymbolTypeAnnotation
  | ThisTypeAnnotation
  | TupleTypeAnnotation
  | TypeReferenceAnnotation
  | TypeofTypeAnnotation
  | UnionTypeAnnotation
  | UnknownTypeAnnotation
  | VoidTypeAnnotation;

export default TypeAnnotation;
