/**
 * @autogenerated
 */

import FunctionDeclaration from '../nodes/FunctionDeclaration';
import VariableDeclaration from '../nodes/VariableDeclaration';

type ValueDeclaration = 
  | FunctionDeclaration
  | VariableDeclaration;

export default ValueDeclaration;
